# Generated by Django 4.0.4 on 2022-04-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[(0, 'TERAPEUTA'), (1, 'PACIENTE'), (2, 'RESPONSÁVEL')], max_length=1),
        ),
    ]
