# Generated by Django 4.0.4 on 2022-04-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('adivisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adivisor_fk', to='user.user')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_fk', to='user.user')),
            ],
            bases=('user.user',),
        ),
    ]
