# Generated by Django 4.0.4 on 2022-04-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_finish', models.BooleanField(blank=True, default=False, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SetChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('choose', models.IntegerField()),
                ('physical_help', models.CharField(blank=True, max_length=2, null=True)),
                ('verbal_help', models.CharField(blank=True, max_length=2, null=True)),
                ('answer_date', models.DateField()),
                ('is_right', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
    ]
