# Generated by Django 4.0.4 on 2022-04-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
