# Generated by Django 4.0.4 on 2022-06-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_setchoice_answer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_finish',
        ),
        migrations.AddField(
            model_name='lesson',
            name='right_answer',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
